### ISSUE TITLE
Devstore doesn't respect title attribute on external tiddlers

### ISSUE THREAD

**Issue by jdlrobson** [FND/tiddlyweb-plugins#1]
Create a TiddlyWeb instance which includes a recipe with a path to a tiddler at a url:

tiddler: http://svn.tiddlywiki.org/.../plugin.tid

Where plugin.tid includes the following line.
title: MyPlugin

run dev_instance foo
and boot up the server

Try to navigate to the bag containing MyPlugin.
A NoTiddlerError is thrown as the devstore seems to make the assumption that a title of a tiddler relates to a filename.

Consider the case where you have an external tiddler with a "/" character in the title. You would not be able to encode the name in the filename.

**Comment by FND** [comment]
Since TiddlyWeb's text serialization is the basis for `.tid` files, the _title_
attribute is not meant to be supported.

> Consider the case where you have an external tiddler with a "/" character in
> the title. You would not be able to encode the name in the filename.

The file name could be encoded as `My%2FPlugin`.
