### ISSUE TITLE
Differ throws 500 on bad parameters

### ISSUE THREAD

**Issue by jdlrobson** [FND/tiddlyweb-plugins#2]
It's very easy to break the differ - just give the diff two arguments that don't exist:

http://jon.tiddlyspace.com/diff?rev1=like&rev2=bpie&format=unified

**Comment by cdent** [comment]
_get_tiddler needs to raise HTTP404 when the store raise NoTiddlerError

**Comment by FND** [comment]
differ: ensured that the correct HTTP error is raised

closed by 65428ab2d5390506d3b0456ab83898b679ee01ad
